SELECT F.ID, FN.FISH_NAME, F.LENGTH
FROM FISH_INFO AS  F
    JOIN FISH_NAME_INFO AS FN
    ON F.FISH_TYPE = FN.FISH_TYPE
WHERE F.LENGTH = (
    SELECT MAX(F2.LENGTH)
    FROM FISH_INFO AS F2
    WHERE F2.FISH_TYPE = F.FISH_TYPE
)
ORDER BY F.ID 
